name: Bump Version and Create PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: "New version (e.g. 0.2.3)"
        required: true
        type: string

permissions:
  contents: write  # needed for creating PRs and pushing branches

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install tomlkit
        run: pip install tomlkit

      - name: Set up Git user
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Write version bump script
        run: |
          cat <<EOF > bump_version.py
          from tomlkit import parse, dumps
          
          import sys
          from pathlib import Path
          
          version = sys.argv[1]
          path = Path("pyproject.toml")
          doc = parse(path.read_text())
          
          doc["project"]["version"] = version
          path.write_text(dumps(doc))
          EOF

      - name: Run version bump script
        run: |
          python bump_version.py "${{ github.event.inputs.version }}"

      - name: Commit version bump
        run: |
          git add pyproject.toml
          git commit -m "🔖 Bump version to v${{ github.event.inputs.version }}"

      - name: Create new branch
        run: |
          git checkout -b bump-version-${{ github.event.inputs.version }}

      - name: Push branch to origin
        run: |
          git fetch origin bump-version-${{ github.event.inputs.version }} || true
          git push --force origin bump-version-${{ github.event.inputs.version }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          commit-message: "🔖 Bump version to v${{ github.event.inputs.version }}"
          branch: bump-version-${{ github.event.inputs.version }}
          title: "Bump version to v${{ github.event.inputs.version }}"
          body: |
            This PR bumps the version to v${{ github.event.inputs.version }}.
          base: master
          draft: false
