name: Publish Python Package to PyPI

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - master

  workflow_dispatch:
    inputs:
      version:
        description: "Version number (must match pyproject.toml)"
        required: true
        type: string

jobs:
  publish:
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tools
        run: pip install --upgrade build twine

      - name: Clean dist folder
        run: rm -rf dist/

      - name: Build the package
        run: python -m build

      - name: Check the distribution files
        run: twine check dist/*

      - name: Publish to PyPI
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/* -u __token__ -p $TWINE_PASSWORD
